namespace MinimalRoslynCpg.Contracts;

public enum RoslynCpgEdgeKind
{
    SyntaxChild,
    TokenChild,
    ParameterLink,
    DeclaresSymbol,
    ReferencesSymbol,
    Ref,
    HasType,
    EvalType,
    ReturnsType,
    ContainsSymbol,
    BaseType,
    InheritsFrom,
    RefersToType,
    SyntaxHasOperation,
    OpHasSyntax,
    OpResolvesToSymbol,
    CallTargets,
    AccessesMember,
    DecisionContains,
    DecisionRelation,
    OpChild,
    OpArgument,
    OpInstance,
    OpTarget,
    OpCondition,
    OpBody,
    OpWhenTrue,
    OpWhenFalse,
    CfgNext,
    CfgTrue,
    CfgFalse,
    DataFlow,
}
