namespace MinimalRoslynCpg.Contracts;

/// <summary>
/// 枚举最小 Roslyn CPG builder 产出的节点种类。
/// </summary>
public enum RoslynCpgNodeKind
{
    SyntaxTree,
    SyntaxNode,
    SyntaxToken,
    Method,
    MethodParameter,
    MethodReturn,
    MethodEntry,
    MethodExit,
    TypeDecl,
    TypeRef,
    Reference,
    CallSite,
    MemberAccess,
    DecisionUnit,
    DecisionFragment,
    SymbolNamespace,
    SymbolType,
    SymbolMethod,
    SymbolProperty,
    SymbolField,
    SymbolLocal,
    SymbolParameter,
    SymbolUnknown,
    Operation,
    OpBlock,
    OpInvocation,
    OpArgument,
    OpBinary,
    OpAssignment,
    OpLocalReference,
    OpParameterReference,
    OpFieldReference,
    OpPropertyReference,
    OpLiteral,
    OpReturn,
    OpBreak,
    OpContinue,
    OpSwitch,
    OpTry,
    OpCatch,
    OpConditional,
    OpLoop,
}
