<Project>
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\bin\**;$(MSBuildProjectDirectory)\obj\**;$(MSBuildProjectDirectory)\Build\**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectDirectory)').Replace('\', '/').Contains('/src/'))">
    <BaseOutputPath>$(MSBuildThisFileDirectory)Build\src\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)Build\src\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectDirectory)').Replace('\', '/').Contains('/tests/'))">
    <BaseOutputPath>$(MSBuildThisFileDirectory)Build\test\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)Build\test\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectDirectory)').Replace('\', '/').Contains('/tools/'))">
    <BaseOutputPath>$(MSBuildThisFileDirectory)Build\tools\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)Build\tools\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
