<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ExecutionRuntime.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <Using Include="NLISSN.Core.Decision" />
    <Using Include="NLISSN.Core.Lifting" />
    <Using Include="NLISSN.Core.Marking" />
    <Using Include="NLISSN.Core.Pipeline" />
    <Using Include="NLISSN.Core.Propagation" />
    <ProjectReference Include="..\NLISSN.Infrastructure\Concurrency\NL.Concurrency.csproj" />
    <ProjectReference Include="..\NLISSN.Core\NLISSN.Core.csproj" />
    <ProjectReference Include="..\NLCPG\NLCPG.csproj" />
    <ProjectReference Include="..\NLISSN.Rules\NLISSN.Rules.csproj" />
  </ItemGroup>
</Project>
