using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using NLCPG.Builder;
using NLCPG.Contracts;
using NLCPG.Model;
using RoslynPrototype.Tests.TestCodeSet.Cpg;
using Xunit;

namespace RoslynPrototype.Tests;

// P02 plan-construction and repeated-traversal reuse.
//
// Three independent layers, deliberately kept apart so a pass here cannot be produced by
// accidentally weakening another:
//
//  1. Frozen oracle. Sparse / Collision / JoinLoop are built through the real production path
//     (BuildFromSource) and compared against the complete ordered graph, the candidate
//     publication sequence, the per-method scalar outcome and the raw/unique candidate counts
//     that the PRE-P02 binary produced. P02 must not move any of them.
//
//  2. T2 structural guards. The zero-FactCount short-circuit is a pure skip, so it must be
//     observable as work removed and never as work added: fact-free operations stop visiting
//     candidate predecessors, while an operation that DOES carry a fact keeps the pre-existing
//     "cleared then found empty" path unchanged.
//
//  3. Counter scoping. Per-method probes are not accumulated across methods in one document and
//     not accumulated across repeated BuildFromSource calls on a reused builder.
//
// The oracle is deliberately NOT DataFlowGraphSnapshot + SHA256: Capture() serializes the
// resolved *absolute* FullName, so its hash depends on the process working directory (the
// measurement host runs from the repo root, the test host from Build/test/Debug/net10.0).
// The normalized graph hash below uses only graph-owned raw fields (interned string-table IDs,
// spans, stable anchors) plus the full edge list, so it is working-directory independent while
// still covering the complete ordered graph.
public sealed class DataFlowPlanConstructionReuseTests {
  // Frozen PRE-P02 oracle. Generated by building each fixture through BuildFromSource with
  // document name "measurement/" + fixture + ".cs" (the name the measurement host uses, because
  // the document path is part of the graph identity) and DataFlowDiagnosticMode.Detailed.
  private const string SparseGraphSnapshotVersion =
      "D0537910C3B8EEACCB618C20496C77A8904548C06D43124C8BA7DB5DAF3F8C78";
  private const string SparseNormalizedGraphHash =
      "C7E26A329D33C43D7C2013C87831817E7E5A594DFEF473126F2C096AF94924F4";
  private const string SparsePublicationHash =
      "E19B748F6C755A1C631E2B581B8D46408E3199D935D638EF9D48DC5CC06C12E6";
  private const string SparseMaterialsHash =
      "499FEC91B1D0F4F2C1236FEDDBBA68D00DF7C82009E07FA53B2CB5C45DC5F528";

  private const string CollisionGraphSnapshotVersion =
      "5071C7F2BB489B3B02D5604148D4B5F3604AB21B6EBD94701FA658BFE349F224";
  private const string CollisionNormalizedGraphHash =
      "38A2FDFC10339F734CB0E2AED2A51FD4C0E6D22A8ED95744339BA07C4733436B";
  private const string CollisionPublicationHash =
      "E694D74902E18CACE289FD8F22C725BEAF6E6B1FB24E579B86DC0103CB8DE2C5";
  private const string CollisionMaterialsHash =
      "818E6EF0A50CE1B34E896F50FB8C1C572C2B145E575DF26B63D41AE15A0D3630";

  private const string JoinLoopGraphSnapshotVersion =
      "139EC2649B06985B048F2848E8F45191B7FD1BFC679EDD0DB1F61A58D1081C6E";
  private const string JoinLoopNormalizedGraphHash =
      "259DE9B7BD8B2B2F37A59CA3222339329E975CB296474A087B38611C4C95CA9E";
  private const string JoinLoopPublicationHash =
      "7BFA1965AF6D49477760A4588164033B4D5EA986A1A3C07AE6BC2D9177AF0427";
  private const string JoinLoopMaterialsHash =
      "8301569F7EBF76AE1C4479C08EF72B84B59E3BE29603A57394516B1EA1CF055E";

  [Fact]
  public void BuildFromSource_Sparse_MatchesFrozenPreChangeOracle() {
    var result = Build(DataFlowMeasurementSources.Sparse(), "measurement/Sparse.cs");

    Assert.Equal(SparseGraphSnapshotVersion, result.Graph.GraphSnapshotVersion);
    Assert.Equal(SparseNormalizedGraphHash, NormalizedGraphHash(result.Graph));
    Assert.Equal(SparsePublicationHash, PublicationHash(result.Diagnostic));
    Assert.Equal(SparseMaterialsHash, MaterialsHash(result.Diagnostic));
    Assert.Equal(2218, result.Graph.Nodes.Count());
    Assert.Equal(5441, result.Graph.Edges.Count());
    Assert.Equal(132, result.Graph.Edges.Count(edge => edge.Kind == NLCPGEdgeKind.DataFlow));
    Assert.Equal(132, result.Diagnostic.Metrics.RawCandidateCount);
    Assert.Equal(132, result.Diagnostic.Metrics.UniqueCandidateCount);
    Assert.Equal(132, result.Diagnostic.PublicationOrder.Count);
    Assert.Equal("Complete", result.Diagnostic.ExitReason);
  }

  [Fact]
  public void BuildFromSource_Collision_MatchesFrozenPreChangeOracle() {
    var result = Build(DataFlowMeasurementSources.Collision(), "measurement/Collision.cs");

    Assert.Equal(CollisionGraphSnapshotVersion, result.Graph.GraphSnapshotVersion);
    Assert.Equal(CollisionNormalizedGraphHash, NormalizedGraphHash(result.Graph));
    Assert.Equal(CollisionPublicationHash, PublicationHash(result.Diagnostic));
    Assert.Equal(CollisionMaterialsHash, MaterialsHash(result.Diagnostic));
    Assert.Equal(3759, result.Graph.Nodes.Count());
    Assert.Equal(10021, result.Graph.Edges.Count());
    Assert.Equal(262, result.Graph.Edges.Count(edge => edge.Kind == NLCPGEdgeKind.DataFlow));
    Assert.Equal(424, result.Diagnostic.Metrics.RawCandidateCount);
    Assert.Equal(262, result.Diagnostic.Metrics.UniqueCandidateCount);
    Assert.Equal(262, result.Diagnostic.PublicationOrder.Count);
    Assert.Equal("Complete", result.Diagnostic.ExitReason);
  }

  [Fact]
  public void BuildFromSource_JoinLoop_MatchesFrozenPreChangeOracle() {
    var result = Build(DataFlowMeasurementSources.JoinLoop(), "measurement/JoinLoop.cs");

    Assert.Equal(JoinLoopGraphSnapshotVersion, result.Graph.GraphSnapshotVersion);
    Assert.Equal(JoinLoopNormalizedGraphHash, NormalizedGraphHash(result.Graph));
    Assert.Equal(JoinLoopPublicationHash, PublicationHash(result.Diagnostic));
    Assert.Equal(JoinLoopMaterialsHash, MaterialsHash(result.Diagnostic));
    Assert.Equal(1383, result.Graph.Nodes.Count());
    Assert.Equal(3405, result.Graph.Edges.Count());
    Assert.Equal(68, result.Graph.Edges.Count(edge => edge.Kind == NLCPGEdgeKind.DataFlow));
    Assert.Equal(120, result.Diagnostic.Metrics.RawCandidateCount);
    Assert.Equal(68, result.Diagnostic.Metrics.UniqueCandidateCount);
    Assert.Equal(68, result.Diagnostic.PublicationOrder.Count);
    Assert.Equal("Complete", result.Diagnostic.ExitReason);
  }

  // T1 required guard: a fact-free operation keeps its CFG/fixpoint result but stops reaching
  // candidate predecessors. ZeroFactChain is 24 nested blocks whose declarations are all
  // constants, so every ordered operation is fact-free and every one of them has a real CFG
  // predecessor. RED before T2: CandidatePredecessorVisits and CandidateUnions are 24 (one per
  // operation) with zero skips. GREEN after: both are 0 and every operation is skipped, while
  // the fixpoint still enqueues and dequeues each flow node and the candidate publication is
  // unchanged.
  [Fact]
  public void BuildFromSource_FactFreeOperations_KeepFixpointButSkipCandidatePredecessors() {
    var result = Build(DataFlowMeasurementSources.ZeroFactChain(), "guards/ZeroFactChain.cs");
    var counters = result.Diagnostic.Counters;

    // The short-circuit did fire for every operation...
    Assert.Equal(147, counters["CandidateOperationVisits"]);
    Assert.Equal(147, counters["CandidateZeroFactSkips"]);
    // ...and it removed exactly the candidate-stage predecessor work.
    Assert.Equal(0, counters["CandidatePredecessorVisits"]);
    Assert.Equal(0, counters["CandidateUnions"]);
    Assert.Equal(0, counters["UsedFactVisits"]);
    Assert.Equal(0, counters["TryGetCandidatesCalls"]);

    // The fixpoint is untouched: every flow node still enters and leaves the worklist, and the
    // definition stage still visits every ordered operation.
    Assert.Equal(149, counters["Enqueues"]);
    Assert.Equal(149, counters["Dequeues"]);
    Assert.Equal(149, counters["SetComparisons"]);
    Assert.Equal(26, counters["FixpointPredecessorVisits"]);
    Assert.Equal(147, counters["DefinitionOperationVisits"]);
    Assert.Equal(147, counters["ExplicitOperationVisits"]);
    Assert.Equal(149, result.Diagnostic.Metrics.FlowNodeCount);
    Assert.Equal(24, result.Diagnostic.Metrics.DefinitionCount);

    // And the observable result is unchanged: 28 candidates survive the skip, both raw and
    // unique, because the candidates come from explicit sources and the return boundary.
    Assert.Equal(28, result.Diagnostic.Metrics.RawCandidateCount);
    Assert.Equal(28, result.Diagnostic.Metrics.UniqueCandidateCount);
    Assert.Equal(28, result.Graph.Edges.Count(edge => edge.Kind == NLCPGEdgeKind.DataFlow));
    Assert.Equal("Complete", result.Diagnostic.ExitReason);
  }

  // T1 required guard: a fact-bearing operation whose in-set is empty stays on the ORIGINAL
  // "cleared then found empty" path and must not be reclassified as a zero-fact operation.
  // `Field` is a real direct used fact, so the guard must not fire; the operation clears the
  // incoming slot, finds no predecessors at all, and short-circuits on IsEmpty before walking
  // any used fact. This is the contrast that keeps the two classes distinct.
  [Fact]
  public void BuildFromSource_FactBearingOperationWithEmptyInSet_KeepsOriginalEmptyPath() {
    var result = Build(DataFlowMeasurementSources.FactWithEmptyIncomingSet(),
        "guards/FactWithEmptyIncomingSet.cs");
    var counters = result.Diagnostic.Counters;

    // Not a zero-fact operation: the guard never fires.
    Assert.Equal(0, counters["CandidateZeroFactSkips"]);
    Assert.Equal(3, counters["CandidateOperationVisits"]);
    // Pre-existing empty-in-set behaviour, unchanged by T2: the predecessor loop runs (and
    // finds nothing), then IsEmpty short-circuits before any fact is enumerated.
    Assert.Equal(0, counters["CandidatePredecessorVisits"]);
    Assert.Equal(0, counters["CandidateUnions"]);
    Assert.Equal(0, counters["UsedFactVisits"]);
    Assert.Equal(0, counters["ReturnedCandidates"]);
    // The used fact was still discovered, and the stages T2 must not touch still ran.
    Assert.Equal(1, counters["DirectUsedFacts"]);
    Assert.Equal(3, counters["DefinitionOperationVisits"]);
    Assert.Equal(1, counters["ExplicitSourceVisits"]);
    Assert.Equal(3, counters["ReturnScanVisits"]);
    Assert.Equal(4, result.Diagnostic.Metrics.UniqueCandidateCount);
    Assert.Equal("Complete", result.Diagnostic.ExitReason);
  }

  // The contrast case for the guard above: the same fact-bearing shape, but with a non-empty
  // in-set, so the candidate stage genuinely reaches the index lookup. Together the two tests
  // pin that the short-circuit distinguishes "no fact at all" from "fact but empty in-set".
  [Fact]
  public void BuildFromSource_FactBearingOperationWithInSet_ReachesIndexLookup() {
    var result = Build(DataFlowMeasurementSources.FactWithIncomingSet(),
        "guards/FactWithIncomingSet.cs");
    var counters = result.Diagnostic.Counters;

    Assert.Equal(0, counters["CandidateZeroFactSkips"]);
    Assert.Equal(1, counters["CandidatePredecessorVisits"]);
    Assert.Equal(1, counters["CandidateUnions"]);
    Assert.Equal(1, counters["UsedFactVisits"]);
    Assert.Equal(1, counters["TryGetCandidatesCalls"]);
    Assert.Equal(1, counters["ReturnedCandidates"]);
    Assert.Equal(5, result.Diagnostic.Metrics.UniqueCandidateCount);
  }

  // A method holding both classes at once: the skip must be selective, not all-or-nothing.
  // Measured before T2 CandidatePredecessorVisits is 3, after it is 2; the skips are exactly the
  // 9 fact-free operations.
  [Fact]
  public void BuildFromSource_MixedFactOperations_SkipOnlyTheFactFreeOnes() {
    var result = Build(DataFlowMeasurementSources.AllZeroFactMethod(), "guards/AllZeroFact.cs");
    var counters = result.Diagnostic.Counters;

    Assert.Equal(16, counters["CandidateOperationVisits"]);
    Assert.Equal(9, counters["CandidateZeroFactSkips"]);
    Assert.Equal(2, counters["CandidatePredecessorVisits"]);
    Assert.Equal(2, counters["CandidateUnions"]);
    // The 7 non-skipped operations still ran, and the result did not move.
    Assert.Equal(7, result.Diagnostic.Metrics.RawCandidateCount);
    Assert.Equal(7, result.Diagnostic.Metrics.UniqueCandidateCount);
    Assert.Equal(18, counters["Enqueues"]);
    Assert.Equal(18, counters["Dequeues"]);
  }

  // T5 budget prefix: the T2 skip only removes candidate attempts that could not contribute, so
  // the pre-dedup budget count and the overflow prefix must be identical to the pre-T2 outcome at
  // every boundary. Measured across budgets 1/2/7/8/27/28/29/262/263 on four fixtures: the only
  // difference is the CandidateZeroFactSkips counter itself; raw, unique, published, overflow
  // reason, exit reason and committed DataFlow edges never move.
  [Theory]
  [InlineData(1, "CandidateEdgeLimitExceeded")]
  [InlineData(2, "CandidateEdgeLimitExceeded")]
  [InlineData(7, "CandidateEdgeLimitExceeded")]
  [InlineData(8, "CandidateEdgeLimitExceeded")]
  [InlineData(27, "CandidateEdgeLimitExceeded")]
  [InlineData(28, "Complete")]
  [InlineData(29, "Complete")]
  [InlineData(262, "Complete")]
  [InlineData(263, "Complete")]
  public void BuildFromSource_ZeroFactChainCandidateBudget_KeepsBudgetPrefix(int budget,
      string expectedExit) {
    var result = Build(DataFlowMeasurementSources.ZeroFactChain(), "measurement/ZeroFactChain.cs",
        budget);

    Assert.Equal(expectedExit, result.Diagnostic.ExitReason);
    Assert.Equal(expectedExit == "Complete" ? "None" : "CandidateEdgeLimitExceeded",
        result.Diagnostic.Metrics.OverflowReason.ToString());
    if (expectedExit == "Complete") {
      // The full 28-candidate set survives the 147 skipped operations.
      Assert.Equal(28, result.Diagnostic.Metrics.RawCandidateCount);
      Assert.Equal(28, result.Diagnostic.Metrics.UniqueCandidateCount);
      Assert.Equal(28, result.Diagnostic.PublicationOrder.Count);
      Assert.Equal(28, result.Graph.Edges.Count(edge => edge.Kind == NLCPGEdgeKind.DataFlow));
    } else {
      // Truncated at the budget, and the computation is pre-dedup: one over the budget is
      // attempted, then rejected, so nothing is published or committed.
      Assert.Equal(budget + 1, result.Diagnostic.Metrics.RawCandidateCount);
      Assert.Equal(budget, result.Diagnostic.Metrics.UniqueCandidateCount);
      Assert.Empty(result.Diagnostic.PublicationOrder);
      Assert.DoesNotContain(result.Graph.Edges, edge => edge.Kind == NLCPGEdgeKind.DataFlow);
    }
    // The guard's own counter is method-local and unaffected by the budget.
    Assert.Equal(147, result.Diagnostic.Counters["CandidateZeroFactSkips"]);
  }

  // T5 DOP equivalence: parallel solving must not change the observable result. DOP=2 is an
  // equivalence check only; all timing evidence is taken at DOP=1.
  [Fact]
  public void BuildFromSource_CollisionAtDopTwo_MatchesDopOne() {
    var serial = Build(DataFlowMeasurementSources.Collision(), "measurement/Collision.cs");
    var parallel = Build(DataFlowMeasurementSources.Collision(), "measurement/Collision.cs",
        degreeOfParallelism: 2);

    Assert.Equal(serial.Diagnostic.Metrics.UniqueCandidateCount,
        parallel.Diagnostic.Metrics.UniqueCandidateCount);
    Assert.Equal(serial.Diagnostic.Metrics.RawCandidateCount,
        parallel.Diagnostic.Metrics.RawCandidateCount);
    Assert.Equal(serial.Diagnostic.Metrics.OverflowReason,
        parallel.Diagnostic.Metrics.OverflowReason);
    Assert.Equal(serial.Diagnostic.ExitReason, parallel.Diagnostic.ExitReason);
    Assert.Equal(PublicationHash(serial.Diagnostic), PublicationHash(parallel.Diagnostic));
    Assert.Equal(serial.Graph.GraphSnapshotVersion, parallel.Graph.GraphSnapshotVersion);
    Assert.Equal(NormalizedGraphHash(serial.Graph), NormalizedGraphHash(parallel.Graph));
  }

  // Counters must be method-local: neither accumulated across the two methods of one document
  // nor across repeated BuildFromSource calls on a reused builder. AllZeroFactMethod is used
  // because it contains BOTH classes (9 fact-free skips and 2 fact-bearing predecessor visits),
  // so a leaked counter would move one of them to 18 / 4.
  [Fact]
  public void BuildFromSource_TwoMethodsAndRepeatedBuilds_KeepCountersMethodLocal() {
    var builder = CreateBuilder();
    string doubled = DataFlowMeasurementSources.AllZeroFactMethod()
            .Replace("static int Run", "static int First")
        + DataFlowMeasurementSources.AllZeroFactMethod().Replace("class Sample", "class Other");

    builder.BuildFromSource(doubled, "guards/TwoMethods.cs");
    Assert.Equal(2, builder.LastDataFlowDiagnostics.Count);
    var first = builder.LastDataFlowDiagnostics[0].Counters;
    var second = builder.LastDataFlowDiagnostics[1].Counters;
    Assert.Equal(first, second);
    // Exactly one method's worth of each, not the sum of both.
    Assert.Equal(9, first["CandidateZeroFactSkips"]);
    Assert.Equal(2, first["CandidatePredecessorVisits"]);
    Assert.Equal(16, first["CandidateOperationVisits"]);

    builder.BuildFromSource(DataFlowMeasurementSources.AllZeroFactMethod(), "guards/Repeat.cs");
    var firstRun = Assert.Single(builder.LastDataFlowDiagnostics).Counters;
    builder.BuildFromSource(DataFlowMeasurementSources.AllZeroFactMethod(), "guards/Repeat.cs");
    var secondRun = Assert.Single(builder.LastDataFlowDiagnostics).Counters;
    Assert.Equal(firstRun, secondRun);
    Assert.Equal(9, secondRun["CandidateZeroFactSkips"]);
    Assert.Equal(2, secondRun["CandidatePredecessorVisits"]);
  }

  private static (NLCPGGraph Graph, DataFlowDiagnosticResult Diagnostic) Build(
      string source, string document, int? candidateBudget = null, int degreeOfParallelism = 1) {
    var builder = CreateBuilder(candidateBudget, degreeOfParallelism);
    var graph = builder.BuildFromSource(source, document);
    return (graph, Assert.Single(builder.LastDataFlowDiagnostics));
  }

  private static NLCPGBuilder CreateBuilder(int? candidateBudget = null,
      int degreeOfParallelism = 1) {
    var dataFlowOptions = NLCPGDataFlowOptions.Unbounded;
    if (candidateBudget is { } budget) {
      dataFlowOptions = dataFlowOptions with { MaxCandidateEdgesPerMethod = budget };
    }

    return new NLCPGBuilder(NLCPGBuilderOptions.CreateDefault() with {
      MaxDegreeOfParallelism = degreeOfParallelism,
      LargeFileLineThreshold = 1, LargeFileMethodThreshold = 1,
      LargeMethodLineSpanThreshold = 1, SyntaxLargeFileLineThreshold = 1,
      DataFlowOptions = dataFlowOptions,
    }) { DataFlowDiagnostics = new(DataFlowDiagnosticMode.Detailed, "reuse", "fixture") };
  }

  // The same serialization the measurement host uses, so the frozen publication identity can be
  // compared without re-deriving the host's JSON options.
  private static readonly JsonSerializerOptions JsonOptions = new() {
    Converters = { new JsonStringEnumConverter() },
  };

  private static string PublicationHash(DataFlowDiagnosticResult diagnostic) {
    return Sha256(JsonSerializer.Serialize(diagnostic.PublicationOrder, JsonOptions));
  }

  private static string MaterialsHash(DataFlowDiagnosticResult diagnostic) {
    return Sha256(JsonSerializer.Serialize(new {
      diagnostic.Document, diagnostic.MethodSignature, diagnostic.SpanStart, diagnostic.SpanEnd,
      diagnostic.StableOrder, diagnostic.Metrics, diagnostic.ExitReason,
    }, JsonOptions));
  }

  // Path-independent normalized graph: raw graph-owned fields plus the complete ordered edge
  // list, with no resolved absolute file path.
  private static string NormalizedGraphHash(NLCPGGraph graph) {
    return Sha256(JsonSerializer.Serialize(new {
      Nodes = graph.Nodes.Select(node => new {
        node.Kind, node.NameId, node.FullNameId, node.SignatureId, node.DispatchKind,
        node.TypeFullNameId, node.FilePathId, node.SpanStart, node.SpanEnd, node.IsImplicit,
        node.NodeId, node.StableAnchor,
      }).ToArray(),
      Edges = graph.Edges.ToArray(),
    }, JsonOptions));
  }

  private static string Sha256(string payload) {
    return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(payload)));
  }
}
