namespace NLCPG.Contracts;

/// 枚举NLCPG builder 产出的边种类。
public enum NLCPGEdgeKind
{
    SyntaxChild,
    TokenChild,
    ParameterLink,
    DeclaresSymbol,
    ReferencesSymbol,
    Ref,
    HasType,
    EvalType,
    ReturnsType,
    ContainsSymbol,
    BaseType,
    InheritsFrom,
    RefersToType,
    SyntaxHasOperation,
    OpHasSyntax,
    OpResolvesToSymbol,
    CallTargets,
    AccessesMember,
    DecisionContains,
    DecisionRelation,
    OpChild,
    OpArgument,
    OpInstance,
    OpTarget,
    OpCondition,
    OpBody,
    OpWhenTrue,
    OpWhenFalse,
    CfgNext,
    CfgTrue,
    CfgFalse,
    DataFlow,
    InterproceduralDataFlow,
    Dominates,
    PostDominates,
    ControlDependence,
}
