namespace NLCPG.Contracts;

/// 枚举NLCPG builder 产出的节点种类。
public enum NLCPGNodeKind
{
    SyntaxTree,
    SyntaxNode,
    SyntaxToken,
    Method,
    MethodParameter,
    MethodReturn,
    MethodEntry,
    MethodExit,
    TypeDecl,
    TypeRef,
    Reference,
    CallSite,
    MemberAccess,
    DecisionUnit,
    DecisionFragment,
    SymbolNamespace,
    SymbolType,
    SymbolMethod,
    SymbolProperty,
    SymbolField,
    SymbolLocal,
    SymbolParameter,
    SymbolUnknown,
    Operation,
    OpBlock,
    OpInvocation,
    OpArgument,
    OpBinary,
    OpAssignment,
    OpLocalReference,
    OpParameterReference,
    OpFieldReference,
    OpPropertyReference,
    OpLiteral,
    OpReturn,
    OpBreak,
    OpContinue,
    OpSwitch,
    OpTry,
    OpCatch,
    OpConditional,
    OpLoop,
}
