<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <Using Include="NLISSN.Core.Decision" />
    <Using Include="NLISSN.Core.Lifting" />
    <Using Include="NLISSN.Core.Marking" />
    <Using Include="NLISSN.Core.Pipeline" />
    <Using Include="NLISSN.Core.Propagation" />
    <ProjectReference Include="..\NLISSN.Infrastructure\Concurrency\NL.Concurrency.csproj" />
    <ProjectReference Include="..\NLISSN.Rule.Generator\NLISSN.Rule.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\NLISSN.Core\NLISSN.Core.csproj" />
    <ProjectReference Include="..\NLCPG\NLCPG.csproj" />
  </ItemGroup>
</Project>
