namespace Rules;

public static partial class DeleteClassRuleIds
{
  public const string DefaultDeleteProposalRuleId = DeleteClassRuleMetadata.DefaultDeleteProposalRuleId;
  public const string ControlStructureProposalRuleId = DeleteClassRuleMetadata.ControlStructureProposalRuleId;
  public const string IfStructureProposalRuleId = DeleteClassRuleMetadata.IfStructureProposalRuleId;
  public const string TypeSyntaxDeclarationProposalRuleId = DeleteClassRuleMetadata.TypeSyntaxDeclarationProposalRuleId;
  public const string MethodReturnTypeProposalRuleId = DeleteClassRuleMetadata.MethodReturnTypeProposalRuleId;
  public const string PublicMethodReturnTypeProposalRuleId = DeleteClassRuleMetadata.PublicMethodReturnTypeProposalRuleId;
  public const string ParameterProposalRuleId = DeleteClassRuleMetadata.ParameterProposalRuleId;
  public const string PrivateMethodParameterShrinkProposalRuleId = DeleteClassRuleMetadata.PrivateMethodParameterShrinkProposalRuleId;
  public const string NamedArgumentMethodParameterShrinkProposalRuleId = DeleteClassRuleMetadata.NamedArgumentMethodParameterShrinkProposalRuleId;
  public const string OptionalParameterDefaultedMethodShrinkProposalRuleId = DeleteClassRuleMetadata.OptionalParameterDefaultedMethodShrinkProposalRuleId;
  public const string ParamsMethodParameterShrinkProposalRuleId = DeleteClassRuleMetadata.ParamsMethodParameterShrinkProposalRuleId;
  public const string PublicMethodParameterShrinkProposalRuleId = DeleteClassRuleMetadata.PublicMethodParameterShrinkProposalRuleId;
  public const string LocalFunctionParameterShrinkProposalRuleId = DeleteClassRuleMetadata.LocalFunctionParameterShrinkProposalRuleId;
  public const string NamedArgumentLocalFunctionParameterShrinkProposalRuleId = DeleteClassRuleMetadata.NamedArgumentLocalFunctionParameterShrinkProposalRuleId;
  public const string OptionalParameterDefaultedLocalFunctionShrinkProposalRuleId = DeleteClassRuleMetadata.OptionalParameterDefaultedLocalFunctionShrinkProposalRuleId;
  public const string DelegateParameterShrinkProposalRuleId = DeleteClassRuleMetadata.DelegateParameterShrinkProposalRuleId;
  public const string IndexerParameterShrinkProposalRuleId = DeleteClassRuleMetadata.IndexerParameterShrinkProposalRuleId;
  public const string NamedArgumentIndexerParameterShrinkProposalRuleId = DeleteClassRuleMetadata.NamedArgumentIndexerParameterShrinkProposalRuleId;
  public const string MethodGroupDelegateParameterShrinkProposalRuleId = DeleteClassRuleMetadata.MethodGroupDelegateParameterShrinkProposalRuleId;
  public const string LambdaDelegateParameterShrinkProposalRuleId = DeleteClassRuleMetadata.LambdaDelegateParameterShrinkProposalRuleId;
  public const string DelegateInvocationChainParameterShrinkProposalRuleId = DeleteClassRuleMetadata.DelegateInvocationChainParameterShrinkProposalRuleId;
  public const string ExtensionReceiverNonFirstParameterShrinkProposalRuleId = DeleteClassRuleMetadata.ExtensionReceiverNonFirstParameterShrinkProposalRuleId;
  public const string PublicParameterProposalRuleId = DeleteClassRuleMetadata.PublicParameterProposalRuleId;
  public const string InterfaceMethodProposalRuleId = DeleteClassRuleMetadata.InterfaceMethodProposalRuleId;
  public const string InterfacePropertyProposalRuleId = DeleteClassRuleMetadata.InterfacePropertyProposalRuleId;
  public const string InterfaceEventProposalRuleId = DeleteClassRuleMetadata.InterfaceEventProposalRuleId;
  public const string InterfaceIndexerProposalRuleId = DeleteClassRuleMetadata.InterfaceIndexerProposalRuleId;
  public const string DelegateProposalRuleId = DeleteClassRuleMetadata.DelegateProposalRuleId;
  public const string ExtensionReceiverProposalRuleId = DeleteClassRuleMetadata.ExtensionReceiverProposalRuleId;
  public const string BaseTypeProposalRuleId = DeleteClassRuleMetadata.BaseTypeProposalRuleId;
  public const string GenericTypeArgumentProposalRuleId = DeleteClassRuleMetadata.GenericTypeArgumentProposalRuleId;
}
