namespace TerrariaTools.Dome.Core.Cpg;

public static class BuiltinSchema
{
    public static CpgSchema Create()
    {
        return new CpgSchema(
            Layers:
            [
                new CpgLayerSchema("base", "Base layer."),
                new CpgLayerSchema("controlflow", "Control flow layer.", ["base"]),
                new CpgLayerSchema("typerel", "Type relations layer.", ["base"]),
                new CpgLayerSchema("callgraph", "Call graph layer.", ["typerel"]),
            ],
            Nodes:
            [
                new CpgNodeSchema(
                    "META_DATA",
                    "MetaDataNode",
                    "StoredNode",
                    [],
                    ["LANGUAGE", "OVERLAYS", "ROOT", "VERSION"],
                    "base"),
                new CpgNodeSchema(
                    "NAMESPACE",
                    "NamespaceNode",
                    "StoredNode",
                    [],
                    ["NAME", "FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "NAMESPACE_BLOCK",
                    "NamespaceBlockNode",
                    "AstNode",
                    [],
                    ["NAME", "FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "FILE",
                    "FileNode",
                    "StoredNode",
                    [],
                    ["PATH", "NAME"],
                    "base"),
                new CpgNodeSchema(
                    "METHOD",
                    "MethodNode",
                    "AstNode",
                    ["ICfgNode", "IDeclarationNode"],
                    ["NAME", "CONTAINING_TYPE_NAME", "RETURN_TYPE_NAME", "FULL_NAME", "SIGNATURE", "TYPE_FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "MEMBER",
                    "MemberNode",
                    "AstNode",
                    ["IDeclarationNode"],
                    ["NAME", "TYPE_FULL_NAME", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "METHOD_PARAMETER_IN",
                    "MethodParameterInNode",
                    "AstNode",
                    ["ICfgNode", "IDeclarationNode"],
                    ["METHOD_NAME", "NAME", "ORDER", "TYPE_FULL_NAME", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "METHOD_PARAMETER_OUT",
                    "MethodParameterOutNode",
                    "AstNode",
                    ["ICfgNode", "IDeclarationNode"],
                    ["METHOD_NAME", "NAME", "ORDER", "TYPE_FULL_NAME", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "METHOD_RETURN",
                    "MethodReturnNode",
                    "AstNode",
                    ["ICfgNode"],
                    ["METHOD_NAME", "TYPE_FULL_NAME", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "LOCAL",
                    "LocalNode",
                    "AstNode",
                    ["ICfgNode", "IDeclarationNode"],
                    ["METHOD_NAME", "NAME", "ORDER", "TYPE_FULL_NAME", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "TYPE",
                    "TypeNode",
                    "StoredNode",
                    [],
                    ["FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "TYPE_REF",
                    "TypeRefNode",
                    "AstNode",
                    [],
                    ["TYPE_FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "TYPE_DECL",
                    "TypeDeclNode",
                    "AstNode",
                    [],
                    ["NAME", "BASE_TYPE_NAME", "FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "BLOCK",
                    "BlockNode",
                    "AstNode",
                    [],
                    ["METHOD_NAME", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "CALL",
                    "CallNode",
                    "ExpressionNode",
                    [],
                    ["OWNER_METHOD_NAME", "TARGET_METHOD_NAME", "ORDER", "CONTAINING_TYPE_NAME", "TYPE_FULL_NAME", "RESOLVED_TARGET_METHOD_ID", "METHOD_FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "CONTROL_STRUCTURE",
                    "ControlStructureNode",
                    "AstNode",
                    ["ICfgNode"],
                    ["METHOD_NAME", "CONTROL_STRUCTURE_TYPE", "ORDER", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "RETURN",
                    "ReturnNode",
                    "AstNode",
                    ["ICfgNode"],
                    ["METHOD_NAME", "ORDER", "CONTAINING_TYPE_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "FIELD_IDENTIFIER",
                    "FieldIdentifierNode",
                    "ExpressionNode",
                    [],
                    ["NAME", "TYPE_FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "METHOD_REF",
                    "MethodRefNode",
                    "ExpressionNode",
                    [],
                    ["METHOD_NAME", "TYPE_FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "IDENTIFIER",
                    "IdentifierNode",
                    "ExpressionNode",
                    [],
                    ["NAME", "ORDER", "TYPE_FULL_NAME"],
                    "base"),
                new CpgNodeSchema(
                    "LITERAL",
                    "LiteralNode",
                    "ExpressionNode",
                    [],
                    ["CODE", "ORDER", "TYPE_FULL_NAME"],
                    "base"),
            ],
            Edges:
            [
                new CpgEdgeSchema(
                    "AST",
                    "AstEdge",
                    ["NAMESPACE_BLOCK", "TYPE_DECL", "METHOD", "BLOCK", "CALL", "CONTROL_STRUCTURE", "RETURN"],
                    ["TYPE_DECL", "MEMBER", "METHOD", "METHOD_PARAMETER_IN", "METHOD_RETURN", "LOCAL", "BLOCK", "CALL", "CONTROL_STRUCTURE", "RETURN", "IDENTIFIER", "LITERAL", "FIELD_IDENTIFIER", "METHOD_REF", "TYPE_REF"],
                    "base"),
                new CpgEdgeSchema(
                    "ARGUMENT",
                    "ArgumentEdge",
                    ["CALL"],
                    ["IDENTIFIER", "LITERAL", "CALL", "METHOD_REF", "FIELD_IDENTIFIER"],
                    "base"),
                new CpgEdgeSchema(
                    "RECEIVER",
                    "ReceiverEdge",
                    ["CALL"],
                    ["IDENTIFIER", "FIELD_IDENTIFIER"],
                    "base"),
                new CpgEdgeSchema(
                    "REF",
                    "RefEdge",
                    ["IDENTIFIER", "FIELD_IDENTIFIER", "METHOD_REF", "TYPE_REF", "MEMBER", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL"],
                    ["METHOD", "MEMBER", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "LOCAL", "TYPE"],
                    "base"),
                new CpgEdgeSchema(
                    "SOURCE_FILE",
                    "SourceFileEdge",
                    ["NAMESPACE_BLOCK", "TYPE_DECL", "METHOD", "MEMBER"],
                    ["FILE"],
                    "base"),
                new CpgEdgeSchema(
                    "CONTAINS",
                    "ContainsEdge",
                    ["FILE", "NAMESPACE", "TYPE_DECL", "METHOD", "BLOCK"],
                    ["NAMESPACE_BLOCK", "TYPE_DECL", "MEMBER", "METHOD", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "BLOCK", "CALL", "CONTROL_STRUCTURE", "RETURN", "TYPE_REF", "IDENTIFIER", "LITERAL", "FIELD_IDENTIFIER", "METHOD_REF"],
                    "base"),
                new CpgEdgeSchema(
                    "EVAL_TYPE",
                    "EvalTypeEdge",
                    ["CALL", "IDENTIFIER", "LITERAL", "FIELD_IDENTIFIER", "METHOD_REF"],
                    ["TYPE"],
                    "base"),
                new CpgEdgeSchema(
                    "CFG",
                    "CfgEdge",
                    ["METHOD", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "CALL", "CONTROL_STRUCTURE", "RETURN"],
                    ["METHOD", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "CALL", "CONTROL_STRUCTURE", "RETURN"],
                    "controlflow"),
                new CpgEdgeSchema(
                    "DOMINATE",
                    "DominateEdge",
                    ["METHOD", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "CALL", "CONTROL_STRUCTURE", "RETURN"],
                    ["METHOD", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "CALL", "CONTROL_STRUCTURE", "RETURN"],
                    "controlflow"),
                new CpgEdgeSchema(
                    "POST_DOMINATE",
                    "PostDominateEdge",
                    ["METHOD", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "CALL", "CONTROL_STRUCTURE", "RETURN"],
                    ["METHOD", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "CALL", "CONTROL_STRUCTURE", "RETURN"],
                    "controlflow"),
                new CpgEdgeSchema(
                    "CDG",
                    "CdgEdge",
                    ["METHOD", "CONTROL_STRUCTURE"],
                    ["CALL", "CONTROL_STRUCTURE", "RETURN"],
                    "controlflow"),
                new CpgEdgeSchema(
                    "INHERITS_FROM",
                    "InheritsFromEdge",
                    ["TYPE_DECL"],
                    ["TYPE_DECL", "TYPE"],
                    "typerel"),
                new CpgEdgeSchema(
                    "ALIAS_OF",
                    "AliasOfEdge",
                    ["MEMBER", "METHOD_PARAMETER_IN", "METHOD_PARAMETER_OUT", "METHOD_RETURN", "LOCAL", "TYPE_REF"],
                    ["TYPE"],
                    "typerel"),
                new CpgEdgeSchema(
                    "FIELD_ACCESS",
                    "FieldAccessEdge",
                    ["FIELD_IDENTIFIER"],
                    ["MEMBER"],
                    "typerel"),
                new CpgEdgeSchema(
                    "CALL",
                    "CallEdge",
                    ["METHOD"],
                    ["METHOD"],
                    "callgraph"),
            ],
            Properties:
            [
                new CpgPropertySchema("LANGUAGE", "string"),
                new CpgPropertySchema("OVERLAYS", "string[]"),
                new CpgPropertySchema("ROOT", "string"),
                new CpgPropertySchema("VERSION", "string"),
                new CpgPropertySchema("PATH", "string"),
                new CpgPropertySchema("NAME", "string"),
                new CpgPropertySchema("FULL_NAME", "string"),
                new CpgPropertySchema("SIGNATURE", "string"),
                new CpgPropertySchema("METHOD_FULL_NAME", "string"),
                new CpgPropertySchema("TYPE_FULL_NAME", "string"),
                new CpgPropertySchema("METHOD_NAME", "string"),
                new CpgPropertySchema("CONTAINING_TYPE_NAME", "string"),
                new CpgPropertySchema("RETURN_TYPE_NAME", "string"),
                new CpgPropertySchema("BASE_TYPE_NAME", "string"),
                new CpgPropertySchema("OWNER_METHOD_NAME", "string"),
                new CpgPropertySchema("TARGET_METHOD_NAME", "string"),
                new CpgPropertySchema("RESOLVED_TARGET_METHOD_ID", "string"),
                new CpgPropertySchema("ORDER", "int"),
                new CpgPropertySchema("CODE", "string"),
                new CpgPropertySchema("CONTROL_STRUCTURE_TYPE", "string"),
            ]);
    }
}
